services:
  web:
    build:
      dockerfile: .
    container_name: hello
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always
  
  db:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
      
    volumes:
      - postgres-db:/var/lib/postgresql/data
  
volumes: 
  postgres-db:
  